version: "3.8"

services:
  daily-image:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8888"
    volumes:
      - daily-image-volume:/app
    ports:
      - 8888:8888
volumes:
  daily-image-volume:
