version: "3.8"

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/app
      - data:/app/images, /app/db.sqlite3
    ports:
      - 8888:8888
volumes:
  data:
